service: team-page

provider:
    name: aws
    runtime: nodejs4.3
    stage: dev
    region: eu-central-1

# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

functions:
    users:
        handler: handler._users
        events:
            - http:
                path: users
                method: get
                integration: lambda
                cors: true
    staff:
        handler: handler._staff
        events:
            - http:
                path: staff
                method: post
                integration: lambda
                cors: true

resources:
    Resources:
        TemplateBucket:
            Type: AWS::S3::Bucket
            Properties:
                BucketName: team-page-template
        OutputBucket:
            Type: AWS::S3::Bucket
            Properties:
                BucketName: team-page-output
