service: team-page

plugins:
    - serverless-webpack
    - serverless-secrets-plugin

provider:
    name: aws
    runtime: nodejs4.3
    region: eu-central-1
    environment:
        GOOGLE_CLIENT_EMAIL: ${self:custom.secrets.GOOGLE_CLIENT_EMAIL}
        GOOGLE_ADMIN_EMAIL: ${self:custom.secrets.GOOGLE_ADMIN_EMAIL}
        GOOGLE_PRIVATE_KEY: ${self:custom.secrets.GOOGLE_PRIVATE_KEY}
    iamRoleStatements:
        - Effect: Allow
          Action:
            - s3:*
          Resource: "arn:aws:s3:::team-html/*"

custom:
    secrets: ${file(secrets.${opt:stage, self:provider.stage}.yml)}
    webpackIncludeModules: true

functions:
    users:
        handler: handler._users
        events:
            - http:
                path: users
                method: get
                integration: lambda
                cors: true
    staff:
        handler: handler._staff
        events:
            - http:
                path: staff
                method: post
                integration: lambda
                cors: true

resources:
    Resources:
        TeamBucket:
            Type: AWS::S3::Bucket
            Properties:
                AccessControl: PublicRead
                BucketName: team-html
                CorsConfiguration:
                          CorsRules:
                          - AllowedMethods:
                            - GET
                            AllowedOrigins:
                            - "*"
                            AllowedHeaders:
                            - "*"
